font_family JetBrainsMonoNF
font_size 10.0 

cursor_shape block

# background_image ~/Pictures/gruv-sushi-streets.png
# background_image_layout cscaled
# background_tint 0.8

background_opacity 0.4
dynamic_background_opacity yes


# BEGIN_KITTY_THEME
# Osaka Jade
include current-theme.conf
# END_KITTY_THEME
